version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DB_HOST=db
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./logs:/app/logs
      - ./results:/app/results
    networks:
      - app_network

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME:-solar_calc_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    command: postgres -c listen_addresses='*'

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge