# Generated by Django 5.1.7 on 2025-04-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Бренд')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('panel_length', models.FloatField(verbose_name='Довжина панелі')),
                ('panel_width', models.FloatField(verbose_name='Ширина панелі')),
            ],
        ),
    ]
