# Generated by Django 5.1.7 on 2025-04-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_panels'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='datasheet',
            field=models.CharField(default='zzz', max_length=255, verbose_name='Дашбоард'),
            preserve_default=False,
        ),
    ]
