# Generated by Django 5.1.7 on 2025-04-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_panels_datasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panels',
            name='datasheet',
            field=models.CharField(help_text='Шлях до файлу в директорії datasheets', max_length=255, verbose_name='Дашбоард'),
        ),
        migrations.AlterField(
            model_name='panels',
            name='panel_length',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Довжина панелі'),
        ),
        migrations.AlterField(
            model_name='panels',
            name='panel_width',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Ширина панелі'),
        ),
    ]
