# Generated by Django 5.1.7 on 2025-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_panels_datasheet_alter_panels_panel_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batteries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Бренд')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Максимальна потужність')),
                ('is_head', models.BooleanField(default=False, verbose_name='Head')),
                ('is_stand', models.BooleanField(default=False, verbose_name='Стенд')),
                ('datasheet', models.CharField(help_text='Шлях до файлу в директорії datasheets', max_length=255, verbose_name='Дашбоард')),
            ],
        ),
        migrations.CreateModel(
            name='Inverters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Бренд')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('power', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Максимальна потужність')),
                ('phases_count', models.IntegerField(verbose_name='Кількість фаз')),
                ('datasheet', models.CharField(help_text='Шлях до файлу в директорії datasheets', max_length=255, verbose_name='Дашбоард')),
            ],
        ),
    ]
