# Generated by Django 5.1.7 on 2025-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_batteries_inverters'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='panel_height',
            field=models.DecimalField(decimal_places=3, default=30, max_digits=10, verbose_name='Висота панелі'),
            preserve_default=False,
        ),
    ]
