# Generated by Django 5.1.7 on 2025-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_remove_batteries_datasheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='panel_type',
            field=models.CharField(default='Односторонні', max_length=20, verbose_name='Тип'),
        ),
    ]
