# Generated by Django 5.1.7 on 2025-04-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_panels_panel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteries',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='batteries',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='inverters',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='inverters',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='panels',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='panels',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
    ]
