# Generated by Django 5.1.7 on 2025-04-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_alter_batteries_brand_alter_batteries_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverters',
            name='strings_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість стрінгів'),
        ),
    ]
